url: "http://kmlprtsng.github.io"
baseurl: ""
title: Kamalpreet Singh
description: This is my personal blog to share my experience and knowledge
avatar: "/img/center-piece.jpg"

navbar-links:
  Home: ""
  About Me: "aboutme"

author:
  name: Kamalpreet Singh Chauhan
  facebook: yo
  github: kmlprtsng
  twitter: Kamalpreet_kc
  linkedin: kamalpreet-chauhan-787aa038
  stackoverflow: 2451434/kamalpreet
 
footer-links-active:
  rss: true
  facebook: false
  email: false
  twitter: true
  github: true
  linkedin: true
  stackoverflow: true

url-pretty: "KamalpreetSingh.com"
# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "kmlprtsng"

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/London"
markdown: kramdown
highlighter: pygments
permalink: /:year-:month-:day-:title
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."
  
# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
